# Generated by Django 5.1.1 on 2024-09-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerScore',
            new_name='Player',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_name',
            new_name='name',
        ),
    ]
